import 'jquery';
import 'angular2/core';
import 'angular2/platform/browser';
import 'angular2/http';
import 'angular2/common';
import 'angular2/router';
import '@ngrx/store';
import 'toastr';
import 'toastr/build/toastr.css';
import 'font-awesome/css/font-awesome.css';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap';
import 'rxjs';
import 'lodash'