// data
// data: authentication
export const DATA_AUTHENTICATION_SET_AUTHENTICATION: string = "DATA_AUTHENTICATION_SET_AUTHENTICATION";
export const DATA_AUTHENTICATION_CLEAR_AUTHENTICATION: string = "DATA_AUTHENTICATION_CLEAR_AUTHENTICATION";
export const DATA_AUTHENTICATION_LOGOUT: string = "DATA_AUTHENTICATION_LOGOUT";
// data: wines
export const DATA_WINES_ADD: string = "DATA_WINES_ADD";
export const DATA_WINES_REMOVE: string = "DATA_WINES_REMOVE";
export const DATA_WINES_UPDATE: string = "DATA_WINES_UPDATE";
export const DATA_WINES_UPDATE_RATE: string = "DATA_WINES_UPDATE_RATE";
export const DATA_WINES_UPDATE_STOCK: string = "DATA_WINES_UPDATE_STOCK";
export const DATA_WINES_ADD_ALL: string = "DATA_WINES_ADD_ALL";

// containers
// containers: application
export const CONTAINER_APPLICATION_ENABLE_BUSY_FLAG: string = "CONTAINER_APPLICATION_ENABLE_BUSY_FLAG";
export const CONTAINER_APPLICATION_DISABLE_BUSY_FLAG: string = "CONTAINER_APPLICATION_DISABLE_BUSY_FLAG";
// containers: editWinePage
export const CONTAINER_EDITWINEPAGE_SET_WINE: string = "CONTAINER_EDITWINEPAGE_SET_WINE";
export const CONTAINER_EDITWINEPAGE_CLEAR_WINE: string = "CONTAINER_EDITWINEPAGE_CLEAR_WINE";
// containers: collapsableSidebar
export const CONTAINER_COLLAPSABLESIDEBAR_TOGGLE: string = "CONTAINER_COLLAPSABLESIDEBAR_TOGGLE";
// containers: wineSearch
export const CONTAINER_WINESEARCH_UPDATE_FOUND_WINES: string = "CONTAINER_WINESEARCH_UPDATE_FOUND_WINES";
export const CONTAINER_WINESEARCH_CLEAR_FOUND_WINES: string = "CONTAINER_WINESEARCH_CLEAR_FOUND_WINES";